# Generated by Django 4.1.2 on 2022-12-06 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido')),
                ('mail', models.EmailField(max_length=100)),
                ('contraseña', models.CharField(max_length=20, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('imagen', models.ImageField(upload_to='stickers')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[(1, 'En revisión'), (2, 'Aceptado'), (3, 'Rechazado'), (4, 'En preparación'), (5, 'Listo para retirar'), (6, 'Retirado')], max_length=1)),
                ('estado_de_pago', models.CharField(choices=[(1, 'Aceptado'), (2, 'Rechazado')], max_length=1)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StickerApp.comprador')),
            ],
        ),
        migrations.CreateModel(
            name='Item_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('tamaño', models.CharField(choices=[('G', 'Grande'), ('M', 'Mediano'), ('C', 'Chico')], max_length=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StickerApp.pedido')),
                ('sticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StickerApp.sticker')),
            ],
        ),
    ]
