# Generated by Django 4.1.2 on 2022-12-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StickerApp', '0002_sticker_esnovedad_alter_pedido_comprador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_pedido',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item_pedido',
            name='tamaño',
            field=models.CharField(choices=[('G', 'Grande'), ('M', 'Mediano'), ('C', 'Chico')], default='Chico', max_length=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[(1, 'En revisión'), (2, 'Aceptado'), (3, 'Rechazado'), (4, 'En preparación'), (5, 'Listo para retirar'), (6, 'Retirado')], default='En revisión', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_de_pago',
            field=models.CharField(choices=[(1, 'Aceptado'), (2, 'Rechazado'), (3, 'Pendiente')], default='Pendiente', max_length=1),
        ),
    ]
