# Generated by Django 4.1.2 on 2022-12-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StickerApp', '0004_alter_pedido_estado_de_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_pedido',
            name='tamaño',
            field=models.CharField(choices=[('G', 'Grande'), ('M', 'Mediano'), ('C', 'Chico')], default='C', max_length=10),
        ),
    ]
