# Generated by Django 4.1.2 on 2022-12-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StickerApp', '0005_alter_item_pedido_tamaño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_pedido',
            name='tamaño',
            field=models.CharField(choices=[('C', 'Chico'), ('G', 'Grande'), ('M', 'Mediano')], default='C', max_length=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('1', 'En revisión'), ('2', 'Aceptado'), ('3', 'Rechazado'), ('4', 'En preparación'), ('5', 'Listo para retirar'), ('6', 'Retirado')], default='En revisión', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_de_pago',
            field=models.CharField(choices=[('1', 'Pendiente'), ('2', 'Rechazado'), ('3', 'Aceptado')], default='Pendiente', max_length=100),
        ),
    ]
