# Generated by Django 4.1.2 on 2022-12-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StickerApp', '0006_alter_item_pedido_tamaño_alter_pedido_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('1', 'En revisión'), ('2', 'Aceptado'), ('3', 'Rechazado'), ('4', 'En preparación'), ('5', 'Listo para retirar'), ('6', 'Retirado')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_de_pago',
            field=models.CharField(choices=[('1', 'Pendiente'), ('2', 'Rechazado'), ('3', 'Aceptado')], default='1', max_length=100),
        ),
    ]
