# Generated by Django 4.1.2 on 2022-12-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StickerApp', '0007_alter_pedido_estado_alter_pedido_estado_de_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('link_imagen', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
