# Generated by Django 4.1.2 on 2022-12-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StickerApp', '0008_personalizados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizados',
            name='link_imagen',
            field=models.URLField(max_length=1000),
        ),
    ]
